# Generated by Django 5.2.6 on 2025-09-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.IntegerField()),
                ('nome', models.CharField()),
                ('tipos', models.CharField()),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ataque', models.IntegerField()),
                ('nome', models.CharField()),
                ('tipo', models.CharField()),
                ('pp', models.CharField()),
                ('power', models.CharField()),
                ('accuracy', models.CharField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pokemon')),
            ],
        ),
    ]
